name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  discover_tests:
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.discover.outputs.files }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Discover test files
      id: discover
      run: echo "$(find tests -name 'test_*.py' | paste -sd ',' -)"
      env:
        files: ${{ steps.discover.outputs.files }}

  test:
    needs: discover_tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ${{ fromJson(needs.discover_tests.outputs.test_files) }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Add project root to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run pytest
      run: pytest ${{ matrix.test_file }}
