name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Add project root to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Discover test files
      id: discover
      run: echo "$(find tests -name 'test_*.py' | paste -sd ',' -)" > test_files.txt

  test_split:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(steps.discover.outputs.files) }}
    steps:
    - name: pytest
